image: node:latest

stages:
  - deploy

cache:
  paths:
    - node_modules/
  key: '$CI_BUILD_REPO'

deploy-prod:
  stage: deploy
  only:
    - master
  script:
    - npm install -g firebase-tools
    - npm install
    - npm run build
    - firebase use "mlog-gcp" --token $FIREBASE_TOKEN
    - cd ./functions
    - npm install
    - cd ..
    - firebase deploy -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN
